// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQN0mvrdc5dVbm1ab4Ao0AxVptl1--CIU',
    appId: '1:591135577415:web:72a80f94dbc75f9189e862',
    messagingSenderId: '591135577415',
    projectId: 'onboarding-c549a',
    authDomain: 'onboarding-c549a.firebaseapp.com',
    storageBucket: 'examackearpp-c549a.appspot.com',
    measurementId: 'G-Y2PGFHEZJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMViVU2UuCFyDpP77D-zZCUaJmiVR0G0',
    appId: '1:591135577415:android:a17631a1ec992d6d89e862',
    messagingSenderId: '591135577415',
    projectId: 'onboarding-c549a',
    storageBucket: 'onboarding-c549a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIk8axsBtRxK_p80EgUeAAPAJCTt4aXdg',
    appId: '1:591135577415:ios:f2d9400ddbd5219389e862',
    messagingSenderId: '591135577415',
    projectId: 'onboarding-c549a',
    storageBucket: 'onboarding-c549a.appspot.com',
    iosBundleId: 'com.example.onboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQN0mvrdc5dVbm1ab4Ao0AxVptl1--CIU',
    appId: '1:591135577415:web:32d3e827b6e0246389e862',
    messagingSenderId: '591135577415',
    projectId: 'onboarding-c549a',
    authDomain: 'onboarding-c549a.firebaseapp.com',
    storageBucket: 'onboarding-c549a.appspot.com',
    measurementId: 'G-04NRB4XMBK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIk8axsBtRxK_p80EgUeAAPAJCTt4aXdg',
    appId: '1:591135577415:ios:f2d9400ddbd5219389e862',
    messagingSenderId: '591135577415',
    projectId: 'onboarding-c549a',
    storageBucket: 'onboarding-c549a.appspot.com',
    iosBundleId: 'com.example.onboarding',
  );

}